### ISSUE TITLE
Make mesh loading cached

### ISSUE THREAD

**Issue by J-Andersen-UvA** [J-Andersen-UvA/BabylonSignLab#1]
We don't want to reload the mesh for every animation, that would be slow. Therefore, we want to cache the mesh.
Cache the mesh rhymes.

**Comment by rem0g** [comment]
I think Babylon caches itself automatically based on my experiences with onprogress of await BABYLON.SceneLoader.ImportMeshAsync.  You have similair function written, right?

**Comment by rem0g** [comment]
engine.disableManifestCheck = true  in Scene loader disables check if file has manifest and then caches it, so we dont need seperate manifest for every file. 

        BABYLON.Database.IDBStorageEnabled = true; in main.html enables caching. 

Loading speed is improved by 99%
