### ISSUE TITLE
Disable blending for showing glosses only

### ISSUE THREAD

**Issue by rem0g** [J-Andersen-UvA/BabylonSignLab#13]
other glosses is being blended by accident with glosses.

**Comment by J-Andersen-UvA** [comment]
The following issue might solve this problem: #18 

because of the following code in the playAnims function:
        `        // Only blend if there are more than one animation groups
        if (animationIndex != loadedResults.animationGroups.length) {
            animationGroup.enableBlending = true;
        }`

**Comment by J-Andersen-UvA** [comment]
Issue belongs to #18
